### ISSUE TITLE
Not working in Crystal 0.7.1 ?

### ISSUE THREAD

**Issue by sardaukar** [werner/todo_crystal#3]
I get this after cloning, running deps and migrations, and then running app/main.cr : 

<pre>
Undefined symbols for architecture x86_64:
  "_*Main::new:Main", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
  "_*Main@Amatista::Base#process<Main, HTTP::Request>:HTTP::Response", referenced from:
      _~fun_literal_16 in main.o
      _~fun_literal_16 in Main.o
  "_*Main@Amatista::Base#run<Main, Int32>:Nil", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o /var/folders/w5/46z328mx33xfmm4st1mgksq80000gn/T/crystal-run-main.QPYU0o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/main.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/CFileIO.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40Int3241.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Math.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Int3241.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/ArgumentError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40UInt841.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40LibABI5858UnwindException41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/UInt64.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40String41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40String41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/GC.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/String.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/String5858Builder.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Slice40T41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Slice40UInt841.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/IndexOutOfBounds.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/DivisionByZero.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StaticArray40UInt844322241.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Exception.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40Pointer40Void4141.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Pointer40Void4141.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Fiber.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Void41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40Fiber41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Fiber41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Event5858Base.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Scheduler.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Amatista5858Handler.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40String4432Array40String4141.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Hash40K4-4e22cbfaaeaaecc0f6b9a2d2252636f6.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40Amatista5858Route41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Amatista5858Route41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40String4432Hash40String4432String4141.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Hash40K4-2a2961ef23c9f44a5615bb37fc51b40e.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/TasksController.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Char.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StaticArray40UInt84432441.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/CharReader.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/InvalidByteSequenceError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Bool.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Amatista5858Route.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SQLite35858Database.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/LibSQLite35858Flag.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SQLite35858Exception.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40Array4040N-b14d399b76aab256be07db16de594288.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Array404-1410f844c2dad800a17e5c389ad8c47e.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SQLite35858Statement.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SQLite35858ResultSet.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/LibSQLite35858Code.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array4040Nil32124-e91231fa2c102c880c1159137f85222f.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer4040Nil321-c9e45f8de8362ebaeb2a4d6a727f896b.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SQLite35858Type.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Int32.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/PointerIO.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StaticArray40UInt844321241.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/IndexView.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Nil.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Int64.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Float64.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/UInt8.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StaticArray40UInt84432541.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/LayoutView.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Symbol.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/HTTP5858Headers.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40K4432V415858StandardComparator.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40K4432V41585-6ae11b6ee1fda3db47c9c3f0fe007f56.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/HTTP5858Request.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/PointerAppender40T41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/PointerAppender40UInt841.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Regex.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/MatchData.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/HTTP5858Response.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40123UInt644432Symbol1254432Bool41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40Hash40K4-766bdc6ea432dd2739b30f84312c75af.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/123UInt644432Symbol125.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Hash40K4432V41585-4c57993f23870785eccb6bb4de73a8c0.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StringIO.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/NewView.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/MissingKey.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Amatista5858Response.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40123String4432String12541.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40123String4432String12541.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/EditView.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Main.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/HTTP5858Server.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Dir.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/File.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/123String4432String125.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Errno.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/LibEvent25858EventFlags.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/FileDescriptorIO.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/IO5858Error.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/File5858Stat.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/CGI.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Array40MatchData41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Pointer40MatchData41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Exception43.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/TCPServer.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/SocketError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/BufferedIO40T41.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/BufferedIO40TCPSocket4341.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/StaticArray40UInt844321638441.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/TCPSocket43.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/HTTP.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/TCPSocket.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/LEBReader.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/Base645858Error.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/JSON5858ParseException.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/GlobError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/IO5858EOFError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/IO5858Error43.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/TimeFormat5858Error.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/DomainError.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/EmptyEnumerable.o .crystal//Users/bruno/Code/FOREIGN/todo_crystal/app/main.cr/AtExitHandlers.o   -lssl -lsqlite3  -levent -lpcl -lpcre -lgc -lpthread`
</pre>

**Comment by werner** [comment]
Hi, thanks for the issue,  checking this.

**Comment by werner** [comment]
I've made a few changes, I replaced sqlite with postgres and make another changes, please keep making issues if you see any problem and thanks.

**Comment by sardaukar** [comment]
thanks!

**Comment by tkrajcar** [comment]
I'm actually having the same problem, running off this repo's master and `Crystal 0.7.1 [86d387c] (Fri May  1 01:04:41 UTC 2015)`. The output is slightly different, probably due to the changes you mentioned above - so I'll reproduce just in case it's helpful:

Happy to make a new issue if it'd be helpful.

```
Undefined symbols for architecture x86_64:
  "_*Main::new:Main", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
  "_*Main@Amatista::Base#process<Main, HTTP::Request>:HTTP::Response", referenced from:
      _~fun_literal_15 in main.o
      _~fun_literal_15 in Main.o
  "_*Main@Amatista::Base#run<Main, Int32>:Nil", referenced from:
      ___crystal_main in main.o
      ___crystal_main in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by werner** [comment]
Hi, 

Did you remove the .deps folder and .deps.lock file?, you might have an outdated version of amatista.
